[package]
name = "bridge1024-listener"
version.workspace = true
edition.workspace = true

[[bin]]
name = "listener"
path = "src/main.rs"

[dependencies]
bridge1024-core = { path = "../core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
ethers.workspace = true
solana-sdk.workspace = true
solana-client.workspace = true
solana-transaction-status.workspace = true
hex.workspace = true
base64.workspace = true
borsh.workspace = true
axum.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
