[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge1024 = "7mXG6UYSDbo1yC11Hcm4C7ptWM4YppLcDqjSkM5dfihc"
bridge1024_hub = "7cyUjZJgkKrcYM8GRnWrQBHreKE7WMPktSPBVDksAZBB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
