[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge1024 = "59j1516cVrj3dpfVe7zQWrTwufajBNdJ5rYvJH7N2hq1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
