[package]
name = "bridge1024-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
hex.workspace = true
bs58.workspace = true
sha2.workspace = true
ed25519-dalek.workspace = true
ethers.workspace = true
borsh.workspace = true
zeroize.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
