[package]
name = "bridge1024-submitter"
version.workspace = true
edition.workspace = true

[[bin]]
name = "submitter"
path = "src/main.rs"

[dependencies]
bridge1024-core = { path = "../core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
ethers.workspace = true
solana-sdk.workspace = true
solana-client.workspace = true
borsh.workspace = true
hex.workspace = true
bs58.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
axum.workspace = true
reqwest.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
