[package]
name = "solana-core"
version = "0.1.0"
description = "Solana Core Bridge Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_core"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
solana-program = "~1.18"
borsh = "0.10"

[profile.release]
overflow-checks = true

[dev-dependencies]
solana-program-test = "~1.18"
solana-sdk = "~1.18"
tokio = "1"

